[package]
name = "rustls"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
der-parser = "8.2.0"
rustls = "0.21.7"
rustls-pemfile = "1.0.0"
webpki-roots = "0.26.0"
